[package]
name = "ancvm-processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ancvm-isa = { path = "../types" }
ancvm-binary = { path = "../binary" }
syscall-util = { git = "https://github.com/hemashushu/syscall-util.git", tag=""}
dyncall-util = { git = "https://github.com/hemashushu/dyncall-util.git", tag=""}
ancvm-context = { path = "../context" }
libc = "0.2"
