[package]
name = "ancvm-processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ancvm-types = { path = "../types" }
ancvm-binary = { path = "../binary" }
syscall-util = { path = "../../../syscall-util" }
dyncall-util = { path = "../../../dyncall-util" }
ancvm-context = { path = "../context" }
libc = "0.2"
