[workspace]
members = [
    "crates/types",
    "crates/binary",
    "crates/syscall",
    "crates/jit",
    "crates/extcall",
    "crates/bridge",
    "crates/thread",
    "crates/runtime",
    "crates/ancsr",
]

resolver = "2"
