[workspace]
members = [
    "crates/types",
    "crates/binary",
    "crates/syscall_util",
    "crates/extfunc_util",
    "crates/program",
    "crates/runtime",
    "crates/parser",
    "crates/ancsr",
]

resolver = "2"
