[package]
name = "ancvm_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ancvm_types = { path = "../types" }
ancvm_binary = { path = "../binary" }
ancvm_syscall = { path = "../syscall" }
ancvm_extcall = { path = "../extcall" }
ancvm_bridge = { path = "../bridge" }
ancvm_thread = { path = "../thread" }
