[package]
name = "ancvm-isa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ason = "1.3.0"
serde = { version = "1.0.214", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
