// Copyright (c) 2023 Hemashushu <hippospark@gmail.com>, All rights reserved.
//
// This Source Code Form is subject to the terms of
// the Mozilla Public License version 2.0 and additional exceptions,
// more details in file LICENSE and CONTRIBUTING.

use crate::opcode::Opcode;

impl Opcode {
    pub fn get_name(&self) -> &'static str {
        match self {
            Opcode::zero => "zero",
            Opcode::drop => "drop",
            Opcode::duplicate => "duplicate",
            Opcode::swap => "swap",
            Opcode::select_nez => "select_nez",
            //
            Opcode::i32_imm => "i32_imm",
            Opcode::i64_imm => "i64_imm",
            Opcode::f32_imm => "f32_imm",
            Opcode::f64_imm => "f64_imm",
            //
            Opcode::local_load => "local_load",
            Opcode::local_load32 => "local_load32",
            Opcode::local_load32_i16_s => "local_load32_i16_s",
            Opcode::local_load32_i16_u => "local_load32_i16_u",
            Opcode::local_load32_i8_s => "local_load32_i8_s",
            Opcode::local_load32_i8_u => "local_load32_i8_u",
            Opcode::local_load_f64 => "local_load_f64",
            Opcode::local_load32_f32 => "local_load32_f32",
            Opcode::local_store => "local_store",
            Opcode::local_store32 => "local_store32",
            Opcode::local_store16 => "local_store16",
            Opcode::local_store8 => "local_store8",
            //
            Opcode::local_long_load => "local_long_load",
            Opcode::local_long_load32 => "local_long_load32",
            Opcode::local_long_load32_i16_s => "local_long_load32_i16_s",
            Opcode::local_long_load32_i16_u => "local_long_load32_i16_u",
            Opcode::local_long_load32_i8_s => "local_long_load32_i8_s",
            Opcode::local_long_load32_i8_u => "local_long_load32_i8_u",
            Opcode::local_long_load_f64 => "local_long_load_f64",
            Opcode::local_long_load32_f32 => "local_long_load32_f32",
            Opcode::local_long_store => "local_long_store",
            Opcode::local_long_store32 => "local_long_store32",
            Opcode::local_long_store16 => "local_long_store16",
            Opcode::local_long_store8 => "local_long_store8",
            //
            Opcode::data_load => "data_load",
            Opcode::data_load32 => "data_load32",
            Opcode::data_load32_i16_s => "data_load32_i16_s",
            Opcode::data_load32_i16_u => "data_load32_i16_u",
            Opcode::data_load32_i8_s => "data_load32_i8_s",
            Opcode::data_load32_i8_u => "data_load32_i8_u",
            Opcode::data_load_f64 => "data_load_f64",
            Opcode::data_load32_f32 => "data_load32_f32",
            Opcode::data_store => "data_store",
            Opcode::data_store32 => "data_store32",
            Opcode::data_store16 => "data_store16",
            Opcode::data_store8 => "data_store8",
            //
            Opcode::data_long_load => "data_long_load",
            Opcode::data_long_load32 => "data_long_load32",
            Opcode::data_long_load32_i16_s => "data_long_load32_i16_s",
            Opcode::data_long_load32_i16_u => "data_long_load32_i16_u",
            Opcode::data_long_load32_i8_s => "data_long_load32_i8_s",
            Opcode::data_long_load32_i8_u => "data_long_load32_i8_u",
            Opcode::data_long_load_f64 => "data_long_load_f64",
            Opcode::data_long_load32_f32 => "data_long_load32_f32",
            Opcode::data_long_store => "data_long_store",
            Opcode::data_long_store32 => "data_long_store32",
            Opcode::data_long_store16 => "data_long_store16",
            Opcode::data_long_store8 => "data_long_store8",
            //
            Opcode::heap_load => "heap_load",
            Opcode::heap_load32 => "heap_load32",
            Opcode::heap_load32_i16_s => "heap_load32_i16_s",
            Opcode::heap_load32_i16_u => "heap_load32_i16_u",
            Opcode::heap_load32_i8_s => "heap_load32_i8_s",
            Opcode::heap_load32_i8_u => "heap_load32_i8_u",
            Opcode::heap_load_f64 => "heap_load_f64",
            Opcode::heap_load32_f32 => "heap_load32_f32",
            Opcode::heap_store => "heap_store",
            Opcode::heap_store32 => "heap_store32",
            Opcode::heap_store16 => "heap_store16",
            Opcode::heap_store8 => "heap_store8",
            //
            Opcode::i32_trunc_i64 => "i32_trunc_i64",
            Opcode::i64_extend_i32_s => "i64_extend_i32_s",
            Opcode::i64_extend_i32_u => "i64_extend_i32_u",
            Opcode::f32_demote_f64 => "f32_demote_f64",
            Opcode::f64_promote_f32 => "f64_promote_f32",
            //
            Opcode::i32_convert_f32_s => "i32_convert_f32_s",
            Opcode::i32_convert_f32_u => "i32_convert_f32_u",
            Opcode::i32_convert_f64_s => "i32_convert_f64_s",
            Opcode::i32_convert_f64_u => "i32_convert_f64_u",
            Opcode::i64_convert_f32_s => "i64_convert_f32_s",
            Opcode::i64_convert_f32_u => "i64_convert_f32_u",
            Opcode::i64_convert_f64_s => "i64_convert_f64_s",
            Opcode::i64_convert_f64_u => "i64_convert_f64_u",
            //
            Opcode::f32_convert_i32_s => "f32_convert_i32_s",
            Opcode::f32_convert_i32_u => "f32_convert_i32_u",
            Opcode::f32_convert_i64_s => "f32_convert_i64_s",
            Opcode::f32_convert_i64_u => "f32_convert_i64_u",
            Opcode::f64_convert_i32_s => "f64_convert_i32_s",
            Opcode::f64_convert_i32_u => "f64_convert_i32_u",
            Opcode::f64_convert_i64_s => "f64_convert_i64_s",
            Opcode::f64_convert_i64_u => "f64_convert_i64_u",
            //
            Opcode::i32_eqz => "i32_eqz",
            Opcode::i32_nez => "i32_nez",
            Opcode::i32_eq => "i32_eq",
            Opcode::i32_ne => "i32_ne",
            Opcode::i32_lt_s => "i32_lt_s",
            Opcode::i32_lt_u => "i32_lt_u",
            Opcode::i32_gt_s => "i32_gt_s",
            Opcode::i32_gt_u => "i32_gt_u",
            Opcode::i32_le_s => "i32_le_s",
            Opcode::i32_le_u => "i32_le_u",
            Opcode::i32_ge_s => "i32_ge_s",
            Opcode::i32_ge_u => "i32_ge_u",
            Opcode::i64_eqz => "i64_eqz",
            Opcode::i64_nez => "i64_nez",
            Opcode::i64_eq => "i64_eq",
            Opcode::i64_ne => "i64_ne",
            Opcode::i64_lt_s => "i64_lt_s",
            Opcode::i64_lt_u => "i64_lt_u",
            Opcode::i64_gt_s => "i64_gt_s",
            Opcode::i64_gt_u => "i64_gt_u",
            Opcode::i64_le_s => "i64_le_s",
            Opcode::i64_le_u => "i64_le_u",
            Opcode::i64_ge_s => "i64_ge_s",
            Opcode::i64_ge_u => "i64_ge_u",
            Opcode::f32_eq => "f32_eq",
            Opcode::f32_ne => "f32_ne",
            Opcode::f32_lt => "f32_lt",
            Opcode::f32_gt => "f32_gt",
            Opcode::f32_le => "f32_le",
            Opcode::f32_ge => "f32_ge",
            Opcode::f64_eq => "f64_eq",
            Opcode::f64_ne => "f64_ne",
            Opcode::f64_lt => "f64_lt",
            Opcode::f64_gt => "f64_gt",
            Opcode::f64_le => "f64_le",
            Opcode::f64_ge => "f64_ge",
            //
            Opcode::i32_add => "i32_add",
            Opcode::i32_sub => "i32_sub",
            Opcode::i32_mul => "i32_mul",
            Opcode::i32_div_s => "i32_div_s",
            Opcode::i32_div_u => "i32_div_u",
            Opcode::i32_rem_s => "i32_rem_s",
            Opcode::i32_rem_u => "i32_rem_u",
            Opcode::i32_inc => "i32_inc",
            Opcode::i32_dec => "i32_dec",
            Opcode::i64_add => "i64_add",
            Opcode::i64_sub => "i64_sub",
            Opcode::i64_mul => "i64_mul",
            Opcode::i64_div_s => "i64_div_s",
            Opcode::i64_div_u => "i64_div_u",
            Opcode::i64_rem_s => "i64_rem_s",
            Opcode::i64_rem_u => "i64_rem_u",
            Opcode::i64_inc => "i64_inc",
            Opcode::i64_dec => "i64_dec",
            Opcode::f32_add => "f32_add",
            Opcode::f32_sub => "f32_sub",
            Opcode::f32_mul => "f32_mul",
            Opcode::f32_div => "f32_div",
            Opcode::f64_add => "f64_add",
            Opcode::f64_sub => "f64_sub",
            Opcode::f64_mul => "f64_mul",
            Opcode::f64_div => "f64_div",
            //
            Opcode::i32_and => "i32_and",
            Opcode::i32_or => "i32_or",
            Opcode::i32_xor => "i32_xor",
            Opcode::i32_not => "i32_not",
            Opcode::i32_leading_zeros => "i32_leading_zeros",
            Opcode::i32_trailing_zeros => "i32_trailing_zeros",
            Opcode::i32_count_ones => "i32_count_ones",
            Opcode::i32_shift_left => "i32_shift_left",
            Opcode::i32_shift_right_s => "i32_shift_right_s",
            Opcode::i32_shift_right_u => "i32_shift_right_u",
            Opcode::i32_rotate_left => "i32_rotate_left",
            Opcode::i32_rotate_right => "i32_rotate_right",
            Opcode::i64_and => "i64_and",
            Opcode::i64_or => "i64_or",
            Opcode::i64_xor => "i64_xor",
            Opcode::i64_not => "i64_not",
            Opcode::i64_leading_zeros => "i64_leading_zeros",
            Opcode::i64_trailing_zeros => "i64_trailing_zeros",
            Opcode::i64_count_ones => "i64_count_ones",
            Opcode::i64_shift_left => "i64_shift_left",
            Opcode::i64_shift_right_s => "i64_shift_right_s",
            Opcode::i64_shift_right_u => "i64_shift_right_u",
            Opcode::i64_rotate_left => "i64_rotate_left",
            Opcode::i64_rotate_right => "i64_rotate_right",
            //
            Opcode::f32_abs => "f32_abs",
            Opcode::f32_neg => "f32_neg",
            Opcode::f32_ceil => "f32_ceil",
            Opcode::f32_floor => "f32_floor",
            Opcode::f32_round_half_away_from_zero => "f32_round_half_away_from_zero",
            Opcode::f32_trunc => "f32_trunc",
            Opcode::f32_fract => "f32_fract",
            Opcode::f32_sqrt => "f32_sqrt",
            Opcode::f32_cbrt => "f32_cbrt",
            Opcode::f32_pow => "f32_pow",
            Opcode::f32_exp => "f32_exp",
            Opcode::f32_exp2 => "f32_exp2",
            Opcode::f32_ln => "f32_ln",
            Opcode::f32_log => "f32_log",
            Opcode::f32_log2 => "f32_log2",
            Opcode::f32_log10 => "f32_log10",
            Opcode::f32_sin => "f32_sin",
            Opcode::f32_cos => "f32_cos",
            Opcode::f32_tan => "f32_tan",
            Opcode::f32_asin => "f32_asin",
            Opcode::f32_acos => "f32_acos",
            Opcode::f32_atan => "f32_atan",
            Opcode::f64_abs => "f64_abs",
            Opcode::f64_neg => "f64_neg",
            Opcode::f64_ceil => "f64_ceil",
            Opcode::f64_floor => "f64_floor",
            Opcode::f64_round_half_away_from_zero => "f64_round_half_away_from_zero",
            Opcode::f64_trunc => "f64_trunc",
            Opcode::f64_fract => "f64_fract",
            Opcode::f64_sqrt => "f64_sqrt",
            Opcode::f64_cbrt => "f64_cbrt",
            Opcode::f64_pow => "f64_pow",
            Opcode::f64_exp => "f64_exp",
            Opcode::f64_exp2 => "f64_exp2",
            Opcode::f64_ln => "f64_ln",
            Opcode::f64_log => "f64_log",
            Opcode::f64_log2 => "f64_log2",
            Opcode::f64_log10 => "f64_log10",
            Opcode::f64_sin => "f64_sin",
            Opcode::f64_cos => "f64_cos",
            Opcode::f64_tan => "f64_tan",
            Opcode::f64_asin => "f64_asin",
            Opcode::f64_acos => "f64_acos",
            Opcode::f64_atan => "f64_atan",
            //
            Opcode::end => "end",
            Opcode::block => "block",
            Opcode::break_ => "break",
            Opcode::recur => "recur",
            Opcode::block_alt => "block_alt",
            Opcode::block_nez => "block_nez",
            Opcode::break_nez => "break_nez",
            Opcode::recur_nez => "recur_nez",
            //
            Opcode::call => "call",
            Opcode::dcall => "dcall",
            Opcode::ecall => "ecall",
            //
            Opcode::nop => "nop",
            Opcode::debug => "debug",
            Opcode::host_addr_local => "host_addr_local",
            Opcode::host_addr_local_long => "host_addr_local_long",
            Opcode::host_addr_data => "host_addr_data",
            Opcode::host_addr_data_long => "host_addr_data_long",
            Opcode::host_addr_heap => "host_addr_heap",
        }
    }
}
