// Copyright (c) 2023 Hemashushu <hippospark@gmail.com>, All rights reserved.
//
// This Source Code Form is subject to the terms of
// the Mozilla Public License version 2.0 and additional exceptions,
// more details in file LICENSE, LICENSE.additional and CONTRIBUTING.

use crate::opcode::Opcode;

impl Opcode {
    pub fn get_name(&self) -> &'static str {
        match self {
            Opcode::nop => "nop",
            // Opcode::zero => "zero",
            // Opcode::drop => "drop",
            // Opcode::duplicate => "duplicate",
            // Opcode::swap => "swap",
            // Opcode::select_nez => "select_nez",
            //
            Opcode::imm_i32 => "imm_i32",
            Opcode::imm_i64 => "imm_i64",
            Opcode::imm_f32 => "imm_f32",
            Opcode::imm_f64 => "imm_f64",
            //
            Opcode::data_load_i64 => "data_load_i64",
            Opcode::data_load_i32_s => "data_load_i32_s",
            Opcode::data_load_i32_u => "data_load_i32_u",
            Opcode::data_load_i16_s => "data_load_i16_s",
            Opcode::data_load_i16_u => "data_load_i16_u",
            Opcode::data_load_i8_s => "data_load_i8_s",
            Opcode::data_load_i8_u => "data_load_i8_u",
            Opcode::data_load_f64 => "data_load_f64",
            Opcode::data_load_f32 => "data_load_f32",
            Opcode::data_store_i64 => "data_store_i64",
            Opcode::data_store_i32 => "data_store_i32",
            Opcode::data_store_i16 => "data_store_i16",
            Opcode::data_store_i8 => "data_store_i8",
            Opcode::data_store_f64 => "data_store_f64",
            Opcode::data_store_f32 => "data_store_f32",
            //
            Opcode::data_load_extend_i64 => "data_load_extend_i64",
            Opcode::data_load_extend_i32_s => "data_load_extend_i32_s",
            Opcode::data_load_extend_i32_u => "data_load_extend_i32_u",
            Opcode::data_load_extend_i16_s => "data_load_extend_i16_s",
            Opcode::data_load_extend_i16_u => "data_load_extend_i16_u",
            Opcode::data_load_extend_i8_s => "data_load_extend_i8_s",
            Opcode::data_load_extend_i8_u => "data_load_extend_i8_u",
            Opcode::data_load_extend_f64 => "data_load_extend_f64",
            Opcode::data_load_extend_f32 => "data_load_extend_f32",

            Opcode::data_store_extend_i64 => "data_store_extend_i64",
            Opcode::data_store_extend_i32 => "data_store_extend_i32",
            Opcode::data_store_extend_i16 => "data_store_extend_i16",
            Opcode::data_store_extend_i8 => "data_store_extend_i8",
            Opcode::data_store_extend_f64 => "data_store_extend_f64",
            Opcode::data_store_extend_f32 => "data_store_extend_f32",
            //
            Opcode::local_load_i64 => "local_load_64",
            Opcode::local_load_i32_s => "local_load_i32_s",
            Opcode::local_load_i32_u => "local_load_i32_u",
            Opcode::local_load_i16_s => "local_load_i16_s",
            Opcode::local_load_i16_u => "local_load_i16_u",
            Opcode::local_load_i8_s => "local_load_i8_s",
            Opcode::local_load_i8_u => "local_load_i8_u",
            Opcode::local_load_f64 => "local_load_f64",
            Opcode::local_load_f32 => "local_load_f32",
            Opcode::local_store_i64 => "local_store_i64",
            Opcode::local_store_i32 => "local_store_i32",
            Opcode::local_store_i16 => "local_store_i16",
            Opcode::local_store_i8 => "local_store_i8",
            Opcode::local_store_f64 => "local_store_f64",
            Opcode::local_store_f32 => "local_store_f32",
            //
            Opcode::local_load_extend_i64 => "local_load_extend_i64",
            Opcode::local_load_extend_i32_s => "local_load_extend_i32_s",
            Opcode::local_load_extend_i32_u => "local_load_extend_i32_u",
            Opcode::local_load_extend_i16_s => "local_load_extend_i16_s",
            Opcode::local_load_extend_i16_u => "local_load_extend_i16_u",
            Opcode::local_load_extend_i8_s => "local_load_extend_i8_s",
            Opcode::local_load_extend_i8_u => "local_load_extend_i8_u",
            Opcode::local_load_extend_f64 => "local_load_extend_f64",
            Opcode::local_load_extend_f32 => "local_load_extend_f32",
            //
            Opcode::local_store_extend_i64 => "local_store_extend_i64",
            Opcode::local_store_extend_i32 => "local_store_extend_i32",
            Opcode::local_store_extend_i16 => "local_store_extend_i16",
            Opcode::local_store_extend_i8 => "local_store_extend_i8",
            Opcode::local_store_extend_f64 => "local_store_extend_f64",
            Opcode::local_store_extend_f32 => "local_store_extend_f32",
            //
            Opcode::heap_load_i64 => "heap_load_i64",
            Opcode::heap_load_i32_s => "heap_load_i32_s",
            Opcode::heap_load_i32_u => "heap_load_i32_u",
            Opcode::heap_load_i16_s => "heap_load_i16_s",
            Opcode::heap_load_i16_u => "heap_load_i16_u",
            Opcode::heap_load_i8_s => "heap_load_i8_s",
            Opcode::heap_load_i8_u => "heap_load_i8_u",
            Opcode::heap_load_f64 => "heap_load_f64",
            Opcode::heap_load_f32 => "heap_load_f32",
            //
            Opcode::heap_store_i64 => "heap_store_i64",
            Opcode::heap_store_i32 => "heap_store_i32",
            Opcode::heap_store_i16 => "heap_store_i16",
            Opcode::heap_store_i8 => "heap_store_i8",
            Opcode::heap_store_f64 => "heap_store_f64",
            Opcode::heap_store_f32 => "heap_store_f32",
            //
            // Opcode::heap_load_bound_i64 => "heap_load_bound_i64",
            // Opcode::heap_load_bound_i32_s => "heap_load_bound_i32_s",
            // Opcode::heap_load_bound_i32_u => "heap_load_bound_i32_u",
            // Opcode::heap_load_bound_i16_s => "heap_load_bound_i16_s",
            // Opcode::heap_load_bound_i16_u => "heap_load_bound_i16_u",
            // Opcode::heap_load_bound_i8_s => "heap_load_bound_i8_s",
            // Opcode::heap_load_bound_i8_u => "heap_load_bound_i8_u",
            // Opcode::heap_load_bound_f64 => "heap_load_bound_f64",
            // Opcode::heap_load_bound_f32 => "heap_load_bound_f32",
            // //
            // Opcode::heap_store_bound_i64 => "heap_store_bound_i64",
            // Opcode::heap_store_bound_i32 => "heap_store_bound_i32",
            // Opcode::heap_store_bound_i16 => "heap_store_bound_i16",
            // Opcode::heap_store_bound_i8 => "heap_store_bound_i8",
            // Opcode::heap_store_bound_f64 => "heap_store_bound_f64",
            // Opcode::heap_store_bound_f32 => "heap_store_bound_f32",
            //
            Opcode::heap_fill => "heap_fill",
            Opcode::heap_copy => "heap_copy",
            Opcode::heap_capacity => "heap_capacity",
            Opcode::heap_resize => "heap_resize",
            //
            Opcode::truncate_i64_to_i32 => "truncate_i64_to_i32",
            Opcode::extend_i32_s_to_i64 => "extend_i32_s_to_i64",
            Opcode::extend_i32_u_to_i64 => "extend_i32_u_to_i64",
            Opcode::demote_f64_to_f32 => "demote_f64_to_f32",
            Opcode::promote_f32_to_f64 => "promote_f32_to_f64",
            //
            Opcode::convert_f32_to_i32_s => "convert_f32_to_i32_s",
            Opcode::convert_f32_to_i32_u => "convert_f32_to_i32_u",
            Opcode::convert_f64_to_i32_s => "convert_f64_to_i32_s",
            Opcode::convert_f64_to_i32_u => "convert_f64_to_i32_u",
            Opcode::convert_f32_to_i64_s => "convert_f32_to_i64_s",
            Opcode::convert_f32_to_i64_u => "convert_f32_to_i64_u",
            Opcode::convert_f64_to_i64_s => "convert_f64_to_i64_s",
            Opcode::convert_f64_to_i64_u => "convert_f64_to_i64_u",
            //
            Opcode::convert_i32_s_to_f32 => "convert_i32_s_to_f32",
            Opcode::convert_i32_u_to_f32 => "convert_i32_u_to_f32",
            Opcode::convert_i64_s_to_f32 => "convert_i64_s_to_f32",
            Opcode::convert_i64_u_to_f32 => "convert_i64_u_to_f32",
            Opcode::convert_i32_s_to_f64 => "convert_i32_s_to_f64",
            Opcode::convert_i32_u_to_f64 => "convert_i32_u_to_f64",
            Opcode::convert_i64_s_to_f64 => "convert_i64_s_to_f64",
            Opcode::convert_i64_u_to_f64 => "convert_i64_u_to_f64",
            //
            Opcode::eqz_i32 => "eqz_i32",
            Opcode::nez_i32 => "nez_i32",
            Opcode::eq_i32 => "eq_i32",
            Opcode::ne_i32 => "ne_i32",
            Opcode::lt_i32_s => "lt_i32_s",
            Opcode::lt_i32_u => "lt_i32_u",
            Opcode::gt_i32_s => "gt_i32_s",
            Opcode::gt_i32_u => "gt_i32_u",
            Opcode::le_i32_s => "le_i32_s",
            Opcode::le_i32_u => "le_i32_u",
            Opcode::ge_i32_s => "ge_i32_s",
            Opcode::ge_i32_u => "ge_i32_u",
            //
            Opcode::eqz_i64 => "eqz_i64",
            Opcode::nez_i64 => "nez_i64",
            Opcode::eq_i64 => "eq_i64",
            Opcode::ne_i64 => "ne_i64",
            Opcode::lt_i64_s => "lt_i64_s",
            Opcode::lt_i64_u => "lt_i64_u",
            Opcode::gt_i64_s => "gt_i64_s",
            Opcode::gt_i64_u => "gt_i64_u",
            Opcode::le_i64_s => "le_i64_s",
            Opcode::le_i64_u => "le_i64_u",
            Opcode::ge_i64_s => "ge_i64_s",
            Opcode::ge_i64_u => "ge_i64_u",
            //
            Opcode::eq_f32 => "eq_f32",
            Opcode::ne_f32 => "ne_f32",
            Opcode::lt_f32 => "lt_f32",
            Opcode::gt_f32 => "gt_f32",
            Opcode::le_f32 => "le_f32",
            Opcode::ge_f32 => "ge_f32",
            //
            Opcode::eq_f64 => "eq_f64",
            Opcode::ne_f64 => "ne_f64",
            Opcode::lt_f64 => "lt_f64",
            Opcode::gt_f64 => "gt_f64",
            Opcode::le_f64 => "le_f64",
            Opcode::ge_f64 => "ge_f64",
            //
            Opcode::add_i32 => "add_i32",
            Opcode::sub_i32 => "sub_i32",
            Opcode::add_imm_i32 => "add_imm_i32",
            Opcode::sub_imm_i32 => "sub_imm_i32",
            Opcode::mul_i32 => "mul_i32",
            Opcode::div_i32_s => "div_i32_s",
            Opcode::div_i32_u => "div_i32_u",
            Opcode::rem_i32_s => "rem_i32_s",
            Opcode::rem_i32_u => "rem_i32_u",
            //
            Opcode::add_i64 => "add_i64",
            Opcode::sub_i64 => "sub_i64",
            Opcode::add_imm_i64 => "add_imm_i64",
            Opcode::sub_imm_i64 => "sub_imm_i64",
            Opcode::mul_i64 => "mul_i64",
            Opcode::div_i64_s => "div_i64_s",
            Opcode::div_i64_u => "div_i64_u",
            Opcode::rem_i64_s => "rem_i64_s",
            Opcode::rem_i64_u => "rem_i64_u",
            //
            Opcode::add_f32 => "add_f32",
            Opcode::sub_f32 => "sub_f32",
            Opcode::mul_f32 => "mul_f32",
            Opcode::div_f32 => "div_f32",
            //
            Opcode::add_f64 => "add_f64",
            Opcode::sub_f64 => "sub_f64",
            Opcode::mul_f64 => "mul_f64",
            Opcode::div_f64 => "div_f64",
            //
            Opcode::and => "and",
            Opcode::or => "or",
            Opcode::xor => "xor",
            Opcode::not => "not",
            //
            Opcode::leading_zeros_i32 => "leading_zeros_i32",
            Opcode::leading_ones_i32 => "leading_ones_i32",
            Opcode::trailing_zeros_i32 => "trailing_zeros_i32",
            Opcode::count_ones_i32 => "count_ones_i32",
            Opcode::shift_left_i32 => "shift_left_i32",
            Opcode::shift_right_i32_s => "shift_right_i32_s",
            Opcode::shift_right_i32_u => "shift_right_i32_u",
            Opcode::rotate_left_i32 => "rotate_left_i32",
            Opcode::rotate_right_i32 => "rotate_right_i32",
            // Opcode::i64_and => "i64.and",
            // Opcode::i64_or => "i64.or",
            // Opcode::i64_xor => "i64.xor",
            // Opcode::i64_not => "i64.not",
            Opcode::leading_zeros_i64 => "leading_zeros_i64",
            Opcode::leading_ones_i64 => "leading_ones_i64",
            Opcode::trailing_zeros_i64 => "trailing_zeros_i64",
            Opcode::count_ones_i64 => "count_ones_i64",
            Opcode::shift_left_i64 => "shift_left_i64",
            Opcode::shift_right_i64_s => "shift_right_i64_s",
            Opcode::shift_right_i64_u => "shift_right_i64_u",
            Opcode::rotate_left_i64 => "rotate_left_i64",
            Opcode::rotate_right_i64 => "rotate_right_i64",
            //
            Opcode::abs_i32 => "abs_i32",
            Opcode::neg_i32 => "neg_i32",
            Opcode::abs_i64 => "abs_i64",
            Opcode::neg_i64 => "neg_i64",
            //
            Opcode::abs_f32 => "abs_f32",
            Opcode::neg_f32 => "neg_f32",
            Opcode::copysign_f32 => "copysign_f32",
            Opcode::sqrt_f32 => "sqrt_f32",
            Opcode::min_f32 => "min_f32",
            Opcode::max_f32 => "max_f32",
            Opcode::ceil_f32 => "ceil_f32",
            Opcode::floor_f32 => "floor_f32",
            Opcode::round_half_away_from_zero_f32 => "round_half_away_from_zero_f32",
            Opcode::round_half_to_even_f32 => "round_half_to_even_f32",
            Opcode::trunc_f32 => "trunc_f32",
            Opcode::fract_f32 => "fract_f32",
            Opcode::cbrt_f32 => "cbrt_f32",
            Opcode::exp_f32 => "exp_f32",
            Opcode::exp2_f32 => "exp2_f32",
            Opcode::ln_f32 => "ln_f32",
            Opcode::log2_f32 => "log2_f32",
            Opcode::log10_f32 => "log10_f32",
            Opcode::sin_f32 => "sin_f32",
            Opcode::cos_f32 => "cos_f32",
            Opcode::tan_f32 => "tan_f32",
            Opcode::asin_f32 => "asin_f32",
            Opcode::acos_f32 => "acos_f32",
            Opcode::atan_f32 => "atan_f32",
            Opcode::pow_f32 => "pow_f32",
            Opcode::log_f32 => "log_f32",
            //
            Opcode::abs_f64 => "abs_f64",
            Opcode::neg_f64 => "neg_f64",
            Opcode::copysign_f64 => "copysign_f64",
            Opcode::sqrt_f64 => "sqrt_f64",
            Opcode::min_f64 => "min_f64",
            Opcode::max_f64 => "max_f64",
            Opcode::ceil_f64 => "ceil_f64",
            Opcode::floor_f64 => "floor_f64",
            Opcode::round_half_away_from_zero_f64 => "round_half_away_from_zero_f64",
            Opcode::round_half_to_even_f64 => "round_half_to_even_f64",
            Opcode::trunc_f64 => "trunc_f64",
            Opcode::fract_f64 => "fract_f64",
            Opcode::cbrt_f64 => "cbrt_f64",
            Opcode::exp_f64 => "exp_f64",
            Opcode::exp2_f64 => "exp2_f64",
            Opcode::ln_f64 => "ln_f64",
            Opcode::log2_f64 => "log2_f64",
            Opcode::log10_f64 => "log10_f64",
            Opcode::sin_f64 => "sin_f64",
            Opcode::cos_f64 => "cos_f64",
            Opcode::tan_f64 => "tan_f64",
            Opcode::asin_f64 => "asin_f64",
            Opcode::acos_f64 => "acos_f64",
            Opcode::atan_f64 => "atan_f64",
            Opcode::pow_f64 => "pow_f64",
            Opcode::log_f64 => "log_f64",
            //
            Opcode::end => "end",
            Opcode::block => "block",
            Opcode::break_ => "break",
            Opcode::recur => "recur",
            Opcode::block_alt => "block_alt",
            Opcode::block_nez => "block_nez",
            Opcode::break_nez => "break_nez",
            Opcode::recur_nez => "recur_nez",
            //
            Opcode::call => "call",
            Opcode::dyncall => "dyncall",
            Opcode::envcall => "envcall",
            Opcode::syscall => "syscall",
            Opcode::extcall => "extcall",
            //
            Opcode::panic => "panic",
            // Opcode::unreachable => "unreachable",
            // Opcode::trap => "trap",
            // Opcode::capture => "capture",
            //
            Opcode::host_addr_local => "host_addr_local",
            Opcode::host_addr_local_extend => "host_addr_local_extend",
            Opcode::host_addr_data => "host_addr_data",
            Opcode::host_addr_data_extend => "host_addr_data_extend",
            Opcode::host_addr_heap => "host_addr_heap",
            Opcode::host_copy_heap_to_memory => "host_copy_heap_to_memory",
            Opcode::host_copy_memory_to_heap => "host_copy_memory_to_heap",
            Opcode::host_memory_copy => "host_memory_copy",
            Opcode::host_addr_function => "host_addr_function",
        }
    }
}
