[package]
name = "anc-image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anc-isa = { path = "../isa" }
ason = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
